version: '3'
services:
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    ports:
      - 83:80
    depends_on:
      - php
  php:
    image: php:7.4-fpm
    volumes:
    - ./web/:/var/www/html

      
